function validate_phase_correction()
S = exp(1i * linspace(0, pi, 64)).';
pivot = 20;

S0 = applyPhaseCorrection(S, 0, 0, pivot);
assert(max(abs(S0 - S)) < 1e-12, 'Zero phase correction should not change spectrum.');

S1 = applyPhaseCorrection(S, 15, 30, pivot);
assert(isequal(size(S1), size(S)), 'Output size mismatch.');

gPivot = (pivot - pivot) / (numel(S) - 1);
phiPivot = (15 + 30 * gPivot) * pi / 180;
assert(abs(angle(S1(pivot) / S(pivot)) - phiPivot) < 1e-10, 'Pivot phase mismatch.');

vol4D = repmat(reshape(S, [], 1, 1, 1), 1, 4, 3, 2);
meta = struct( ...
    'phaseEnabled', true, ...
    'phaseParams', struct('ph0Deg', 15, 'ph1Deg', 30, 'pivotIndex', pivot));
[vol3D, corrected] = buildIntegratedVolumeFromSpectrum(vol4D, 10:20, meta);
assert(isequal(size(vol3D), [4, 3, 2]), 'Integrated volume size mismatch.');
assert(isequal(size(corrected), size(vol4D)), 'Corrected spectrum size mismatch.');

ph0Map = reshape([10, -25, 40, 5], [2, 2, 1]);
ph1Map = reshape([20, 30, -15, 45], [2, 2, 1]);
pivotMap = reshape([12, 18, 24, 30], [2, 2, 1]);
mapInput = repmat(reshape(S, [], 1, 1, 1), 1, 2, 2, 1);
mapCorrected = applyPhaseCorrection(mapInput, ph0Map, ph1Map, pivotMap);
for x = 1:2
    for y = 1:2
        expected = applyPhaseCorrection(mapInput(:, x, y, 1), ...
            ph0Map(x, y, 1), ph1Map(x, y, 1), pivotMap(x, y, 1));
        assert(max(abs(mapCorrected(:, x, y, 1) - expected)) < 1e-12, ...
            'Voxel-wise phase map application mismatch.');
    end
end

mapMeta = struct( ...
    'phaseEnabled', true, ...
    'phaseMode', 'voxelwise', ...
    'phaseMaps', struct( ...
        'ph0Deg', ph0Map, ...
        'ph1Deg', ph1Map, ...
        'pivotIndex', pivotMap));
[~, storedCorrected] = buildIntegratedVolumeFromSpectrum(mapInput, 10:20, mapMeta);
assert(max(abs(storedCorrected(:) - mapCorrected(:))) < 1e-12, ...
    'Stored voxel-wise phase maps were not applied.');

globalMapMeta = struct( ...
    'phaseEnabled', true, ...
    'phaseMode', 'global', ...
    'phaseParams', struct('ph0Deg', 12, 'ph1Deg', -18, 'pivotIndex', 16));
expandedGlobalMaps = materializePhaseMaps(globalMapMeta, [2, 2, 1], numel(S));
assert(all(expandedGlobalMaps.ph0Deg(:) == 12) ...
    && all(expandedGlobalMaps.ph1Deg(:) == -18) ...
    && all(expandedGlobalMaps.pivotIndex(:) == 16), ...
    'Global phase parameters were not expanded to all voxels.');

mapMeta.phaseMaps.successMask = true(2, 2, 1);
preservedMaps = materializePhaseMaps(mapMeta, [2, 2, 1], numel(S));
assert(isequal(preservedMaps.ph0Deg, ph0Map) ...
    && isequal(preservedMaps.ph1Deg, ph1Map) ...
    && isequal(preservedMaps.pivotIndex, pivotMap), ...
    'Existing voxel-wise phase maps were not preserved.');

disp('phase correction ok');
end
